# Generated by Django 3.1 on 2020-08-25 12:15

from django.db import migrations, models
import django.db.models.deletion
import s3upload.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_filename', s3upload.fields.S3UploadField(blank=True, dest='custom_filename')),
            ],
        ),
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', s3upload.fields.S3UploadField(blank=True, dest='vids')),
                ('image', s3upload.fields.S3UploadField(blank=True, dest='imgs')),
                ('pdf', s3upload.fields.S3UploadField(blank=True, dest='files')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.cat')),
            ],
        ),
    ]
