# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3upload.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_filename', s3upload.fields.S3UploadField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', s3upload.fields.S3UploadField(blank=True)),
                ('image', s3upload.fields.S3UploadField(blank=True)),
                ('pdf', s3upload.fields.S3UploadField(blank=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.Cat')),
            ],
        ),
    ]
