# Generated by Django 3.2.11 on 2022-01-07 15:27

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='custom_filename',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
