name: Test s3direct

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install node deps
        run: npm install

      - name: Install Python deps
        run: pip3 install -r requirements-dev.txt

      - name: Run tests
        run: npm run test
